from enum import StrEnum


# ══════════════════════════════════════════════════════════════════════════════
# Document & Process Enums
# ══════════════════════════════════════════════════════════════════════════════

class DocCategory(StrEnum):
    INTERN = "INTERN"
    INCOMING = "INCOMING"
    OUTGOING = "OUTGOING"
    MEETING = "MEETING"
    QUESTION = "QUESTION"
    MEETING_QUESTION = "MEETING_QUESTION"
    APPEAL = "APPEAL"
    CONTRACT = "CONTRACT"
    CUSTOM = "CUSTOM"


class RequiredFieldEnum(StrEnum):
    ATTACHMENT = "ATTACHMENT"
    OUT_CORRESPONDENT_ORG_NUM = "OUT_CORRESPONDENT_ORG_NUM"
    OUT_CORRESPONDENT_ORG_DATE = "OUT_CORRESPONDENT_ORG_DATE"
    OUT_CORRESPONDENT_NAME = "OUT_CORRESPONDENT_NAME"
    DOC_SIGNERS = "DOC_SIGNERS"
    RECIPIENT_NAME = "RECIPIENT_NAME"
    AFFAIRS = "AFFAIRS"
    CONTRACT_CORRESPONDENT = "CONTRACT_CORRESPONDENT"


class DocumentStatus(StrEnum):  # Status2 в OpenAPI
    DRAFT = "DRAFT"
    NEW = "NEW"
    STATEMENT = "STATEMENT"
    APPROVED = "APPROVED"
    SIGNING = "SIGNING"
    SIGNED = "SIGNED"
    AGREEMENT = "AGREEMENT"
    AGREED = "AGREED"
    REVIEW = "REVIEW"
    REVIEWED = "REVIEWED"
    REGISTRATION = "REGISTRATION"
    REGISTERED = "REGISTERED"
    EXECUTION = "EXECUTION"
    EXECUTED = "EXECUTED"
    DISPATCH = "DISPATCH"
    SENT = "SENT"
    REJECT = "REJECT"
    CANCEL = "CANCEL"
    PREPARATION = "PREPARATION"
    PAPERWORK = "PAPERWORK"
    FORMALIZED = "FORMALIZED"
    ACCEPTANCE = "ACCEPTANCE"
    ACCEPTED = "ACCEPTED"
    CONTRACT_EXECUTION = "CONTRACT_EXECUTION"
    CONTRACT_CLOSED = "CONTRACT_CLOSED"
    ARCHIVE = "ARCHIVE"
    DELETED = "DELETED"
    ALL = "ALL"


class DocumentProcessType(StrEnum):  # Type4 в OpenAPI
    NEW = "NEW"
    AGREEMENT = "AGREEMENT"
    SIGNING = "SIGNING"
    STATEMENT = "STATEMENT"
    REGISTRATION = "REGISTRATION"
    REVIEW = "REVIEW"
    EXECUTION = "EXECUTION"
    DISPATCH = "DISPATCH"
    PREPARATION = "PREPARATION"
    PAPERWORK = "PAPERWORK"
    ACCEPTANCE = "ACCEPTANCE"
    CONTRACT_EXECUTION = "CONTRACT_EXECUTION"


class JobStatus(StrEnum):
    NEW = "NEW"
    AWAITING_CONVERSION = "AWAITING_CONVERSION"
    READY = "READY"
    IN_WORK_CONVERSION = "IN_WORK_CONVERSION"
    COMPLETED = "COMPLETED"
    SIGNED = "SIGNED"
    DISPATCH = "DISPATCH"
    IN_WORK_DISPATCH = "IN_WORK_DISPATCH"
    SENT = "SENT"
    ERROR_CONVERSION = "ERROR_CONVERSION"
    ERROR_DISPATCH = "ERROR_DISPATCH"


class CreateType(StrEnum):
    MANUAL = "MANUAL"
    AISMV = "AISMV"
    DIRECTUM = "DIRECTUM"


class AttachmentType(StrEnum):  # Type1 в OpenAPI
    MAIN_ATTACHMENT = "MAIN_ATTACHMENT"
    ADDITIONAL_ATTACHMENT = "ADDITIONAL_ATTACHMENT"


class AttachmentDocumentType(StrEnum):
    ATTACHMENT = "ATTACHMENT"
    PRINT_DOCUMENT = "PRINT_DOCUMENT"
    PROJECT_SOLUTION = "PROJECT_SOLUTION"
    RATIONALE = "RATIONALE"
    DOCUMENTS_QUESTION = "DOCUMENTS_QUESTION"
    INTRODUCTION_LIST = "INTRODUCTION_LIST"
    AGREEMENT_LIST = "AGREEMENT_LIST"
    DECISION = "DECISION"
    RKK = "RKK"


class DocOperationType(StrEnum):
    """Available operations on entities in a document."""
    DOCUMENT_READ = "DOCUMENT_READ"
    DOCUMENT_DELETE = "DOCUMENT_DELETE"
    DOCUMENT_CHANGE_REGNUMBER = "DOCUMENT_CHANGE_REGNUMBER"
    DOCUMENT_FIELDS_MEETING_QUESTION_UPDATE = "DOCUMENT_FIELDS_MEETING_QUESTION_UPDATE"
    DOCUMENT_QUESTION_RESPONSIBLE_EXECUTOR_UPDATE = "DOCUMENT_QUESTION_RESPONSIBLE_EXECUTOR_UPDATE"
    DOCUMENT_FIELDS_QUESTION_UPDATE = "DOCUMENT_FIELDS_QUESTION_UPDATE"
    DOCUMENT_FIELDS_MEETING_UPDATE = "DOCUMENT_FIELDS_MEETING_UPDATE"
    DOCUMENT_MEETING_INVITEES_UPDATE = "DOCUMENT_MEETING_INVITEES_UPDATE"
    DOCUMENT_CONTRACT_FIELDS_UPDATE = "DOCUMENT_CONTRACT_FIELDS_UPDATE"
    DOCUMENT_CONTRACT_AUTO_PROLONGATION_UPDATE = "DOCUMENT_CONTRACT_AUTO_PROLONGATION_UPDATE"
    DOCUMENT_CONTRACT_TYPICAL_UPDATE = "DOCUMENT_CONTRACT_TYPICAL_UPDATE"
    DOCUMENT_CONTRACT_CORRESPONDENT_UPDATE = "DOCUMENT_CONTRACT_CORRESPONDENT_UPDATE"
    DOCUMENT_CONTRACT_AGREEMENT_UPDATE = "DOCUMENT_CONTRACT_AGREEMENT_UPDATE"
    DOCUMENT_MAIN_FIELDS_UPDATE = "DOCUMENT_MAIN_FIELDS_UPDATE"
    DOCUMENT_MAIN_FIELDS_APPEAL_UPDATE = "DOCUMENT_MAIN_FIELDS_APPEAL_UPDATE"
    DOCUMENT_REPEAT_IDENTICAL_UPDATE = "DOCUMENT_REPEAT_IDENTICAL_UPDATE"
    DOCUMENT_CORRESPONDENT_UPDATE = "DOCUMENT_CORRESPONDENT_UPDATE"
    DOCUMENT_PROCESS_ITEM_UPDATE = "DOCUMENT_PROCESS_ITEM_UPDATE"
    DOCUMENT_PROCESS_MOVE = "DOCUMENT_PROCESS_MOVE"
    DOCUMENT_PROCESS_EXECUTORS_UPDATE = "DOCUMENT_PROCESS_EXECUTORS_UPDATE"
    DOCUMENT_PREPARATION_COMPLETED = "DOCUMENT_PREPARATION_COMPLETED"
    DOCUMENT_PAPERWORK_COMPLETED = "DOCUMENT_PAPERWORK_COMPLETED"
    DOCUMENT_ACCEPTANCE_COMPLETED = "DOCUMENT_ACCEPTANCE_COMPLETED"
    DOCUMENT_TEST = "TEST"
    DOCUMENT_CANCEL = "DOCUMENT_CANCEL"
    DOCUMENT_NEXT_PROCESS = "DOCUMENT_NEXT_PROCESS"
    DOCUMENT_START = "DOCUMENT_START"
    DOCUMENT_ACCESS_GRIEF_UPDATE = "DOCUMENT_ACCESS_GRIEF_UPDATE"
    DOCUMENT_UNDRAFT = "DOCUMENT_UNDRAFT"
    DOCUMENT_PROCESS_STATEMENT = "DOCUMENT_PROCESS_STATEMENT"
    DOCUMENT_PROCESS_SIGNING = "DOCUMENT_PROCESS_SIGNING"
    DOCUMENT_PROCESS_AGREEMENT = "DOCUMENT_PROCESS_AGREEMENT"
    DOCUMENT_PROCESS_CONTRACT_EXECUTION = "DOCUMENT_PROCESS_CONTRACT_EXECUTION"
    DOCUMENT_PROCESS_REVIEW = "DOCUMENT_PROCESS_REVIEW"
    DOCUMENT_PROCESS_REDIRECT_REVIEW = "DOCUMENT_PROCESS_REDIRECT_REVIEW"
    DOCUMENT_PROCESS_SENT = "DOCUMENT_PROCESS_SENT"
    DOCUMENT_PROCESS_REGISTRATION = "DOCUMENT_PROCESS_REGISTRATION"
    DOCUMENT_PROCESS_FREE_REGISTRATION = "DOCUMENT_PROCESS_FREE_REGISTRATION"
    DOCUMENT_PROCESS_REPLACE_EXECUTORS = "DOCUMENT_PROCESS_REPLACE_EXECUTORS"
    DOCUMENT_PROCESS_SWAP_EXECUTORS = "DOCUMENT_PROCESS_SWAP_EXECUTORS"
    DOCUMENT_RESERVE_REGNUMBER = "DOCUMENT_RESERVE_REGNUMBER"
    DOCUMENT_PROCESS_SMDO_REGISTRATION_SKIP = "DOCUMENT_PROCESS_SMDO_REGISTRATION_SKIP"
    DOCUMENT_PROCESS_SMDO_REGISTRATION_REJECT = "DOCUMENT_PROCESS_SMDO_REGISTRATION_REJECT"
    DOCUMENT_SMDO_CREATE_ANSWER = "DOCUMENT_SMDO_CREATE_ANSWER"
    DOCUMENT_CREATE_ANSWER = "DOCUMENT_CREATE_ANSWER"
    DOCUMENT_UPDATE_ACCESS_LIST = "DOCUMENT_UPDATE_ACCESS_LIST"
    DOCUMENT_SMDO_RECREATE = "DOCUMENT_SMDO_RECREATE"
    DOCUMENT_SMDO_RETRY_ACK_DELIVERY = "DOCUMENT_SMDO_RETRY_ACK_DELIVERY"
    DOCUMENT_SMDO_RETRY_DOCUMENT_DELIVERY = "DOCUMENT_SMDO_RETRY_DOCUMENT_DELIVERY"
    DOCUMENT_SMDO_CONFIRM_DELIVERY = "DOCUMENT_SMDO_CONFIRM_DELIVERY"
    DOCUMENT_SMDO_CANCEL_DELIVERY = "DOCUMENT_SMDO_CANCEL_DELIVERY"
    DOCUMENT_LINK_UPDATE = "DOCUMENT_LINK_UPDATE"
    DOCUMENT_INTRODUCTION_CREATE = "DOCUMENT_INTRODUCTION_CREATE"
    DOCUMENT_INTRODUCTION_DELETE = "DOCUMENT_INTRODUCTION_DELETE"
    DOCUMENT_INTRODUCTION_DELETE_ALL = "DOCUMENT_INTRODUCTION_DELETE_ALL"
    DOCUMENT_INTRODUCTION_EXECUTE = "DOCUMENT_INTRODUCTION_EXECUTE"
    DOCUMENT_ADDITIONAL_AGREEMENT_CREATE = "DOCUMENT_ADDITIONAL_AGREEMENT_CREATE"
    DOCUMENT_ADDITIONAL_AGREEMENT_DELETE = "DOCUMENT_ADDITIONAL_AGREEMENT_DELETE"
    DOCUMENT_ADDITIONAL_AGREEMENT_DELETE_ALL = "DOCUMENT_ADDITIONAL_AGREEMENT_DELETE_ALL"
    DOCUMENT_ADDITIONAL_AGREEMENT_EXECUTE = "DOCUMENT_ADDITIONAL_AGREEMENT_EXECUTE"
    DOCUMENT_NEW_VERSION = "DOCUMENT_NEW_VERSION"
    DOCUMENT_CONTROL_CREATE = "DOCUMENT_CONTROL_CREATE"
    DOCUMENT_CONTROL_UPDATE = "DOCUMENT_CONTROL_UPDATE"
    DOCUMENT_CONTROL_REMOVE = "DOCUMENT_CONTROL_REMOVE"
    DOCUMENT_CONTROL_DELETE = "DOCUMENT_CONTROL_DELETE"
    DOCUMENT_RECIPIENT_LIST_UPDATE = "DOCUMENT_RECIPIENT_LIST_UPDATE"
    DOCUMENT_PRINT_REFERATKA = "DOCUMENT_PRINT_REFERATKA"
    DOCUMENT_PRINT_SHEET = "DOCUMENT_PRINT_SHEET"
    DOCUMENT_PRINT = "DOCUMENT_PRINT"
    DOCUMENT_PRINT_ATTACHMENT = "DOCUMENT_PRINT_ATTACHMENT"
    DOCUMENT_PRINT_JOURNAL = "DOCUMENT_PRINT_JOURNAL"
    DOCUMENT_PRINT_INTRODUCTION = "DOCUMENT_PRINT_INTRODUCTION"
    DOCUMENT_PRINT_CONTRACT_EXECUTION = "DOCUMENT_PRINT_CONTRACT_EXECUTION"
    DOCUMENT_PRINT_LINK = "DOCUMENT_PRINT_LINK"
    DOCUMENT_PRINT_MEETING_QUESTION = "DOCUMENT_PRINT_MEETING_QUESTION"
    DOCUMENT_PRINT_ADDITIONAL_AGREEMENT = "DOCUMENT_PRINT_ADDITIONAL_AGREEMENT"
    DOCUMENT_ATTACHMENT_EDS_UPLOAD = "DOCUMENT_ATTACHMENT_EDS_UPLOAD"
    DOCUMENT_ATTACHMENT_EDS_REMOVE = "DOCUMENT_ATTACHMENT_EDS_REMOVE"
    DOCUMENT_ATTACHMENT_EDS_CHECK = "DOCUMENT_ATTACHMENT_EDS_CHECK"
    DOCUMENT_ADD_DOCUMENTS = "DOCUMENT_ADD_DOCUMENTS"
    DOCUMENT_UPDATE_ATTACHMENT = "DOCUMENT_UPDATE_ATTACHMENT"
    DOCUMENT_DELETE_ATTACHMENT = "DOCUMENT_DELETE_ATTACHMENT"
    DOCUMENT_READ_ATTACHMENT = "DOCUMENT_READ_ATTACHMENT"
    DOCUMENT_UPDATE_ADDITIONAL_ATTACHMENT = "DOCUMENT_UPDATE_ADDITIONAL_ATTACHMENT"
    DOCUMENT_DELETE_ADDITIONAL_ATTACHMENT = "DOCUMENT_DELETE_ADDITIONAL_ATTACHMENT"
    DOCUMENT_READ_ADDITIONAL_ATTACHMENT = "DOCUMENT_READ_ADDITIONAL_ATTACHMENT"
    DOCUMENT_NOMENCLATURE_AFFAIR_UPDATE = "DOCUMENT_NOMENCLATURE_AFFAIR_UPDATE"
    DOCUMENT_WRITE_OFF_NOMENCLATURE_AFFAIR_UPDATE = "DOCUMENT_WRITE_OFF_NOMENCLATURE_AFFAIR_UPDATE"
    DOCUMENT_CHANGE_AUTHOR = "DOCUMENT_CHANGE_AUTHOR"
    DOCUMENT_EXTRACT_NOMENCLATURE_AFFAIR_UPDATE = "DOCUMENT_EXTRACT_NOMENCLATURE_AFFAIR_UPDATE"
    DOCUMENT_IN_ARCHIVE_UPDATE = "DOCUMENT_IN_ARCHIVE_UPDATE"
    DOCUMENT_TASK_CREATE = "DOCUMENT_TASK_CREATE"
    DOCUMENT_FOLDER_USER = "DOCUMENT_FOLDER_USER"
    DOCUMENT_TO_PREPARATION = "DOCUMENT_TO_PREPARATION"
    DOCUMENT_PREPARATION_NOTIFY = "DOCUMENT_PREPARATION_NOTIFY"
    DOCUMENT_REDO_PROTOCOL = "DOCUMENT_REDO_PROTOCOL"
    DOCUMENT_LIST_QUESTIONS_UPDATE = "DOCUMENT_LIST_QUESTIONS_UPDATE"
    DOCUMENT_SPEAKERS_MEETING_QUESTION_UPDATE = "DOCUMENT_SPEAKERS_MEETING_QUESTION_UPDATE"
    DOCUMENT_NOTIFY_MEETING_QUESTION = "DOCUMENT_NOTIFY_MEETING_QUESTION"
    DOCUMENT_CONTRACT_RESPONSIBLE = "DOCUMENT_CONTRACT_RESPONSIBLE"
    DOCUMENT_UPDATE_CUSTOM_FIELDS = "DOCUMENT_UPDATE_CUSTOM_FIELDS"
    TASK_UPDATE = "TASK_UPDATE"
    TASK_PERIOD_UPDATE = "TASK_PERIOD_UPDATE"
    TASK_EXECUTOR_UPDATE = "TASK_EXECUTOR_UPDATE"
    TASK_EXECUTE_ONE_FOR_ALL = "TASK_EXECUTE_ONE_FOR_ALL"
    TASK_REVISION = "TASK_REVISION"
    TASK_DELETE = "TASK_DELETE"
    TASK_EXECUTE_CHANGE_DATE_REQUEST = "TASK_EXECUTE_CHANGE_DATE_REQUEST"
    TASK_EXECUTE = "TASK_EXECUTE"
    TASK_CHANGE_DATE_REQUEST = "TASK_CHANGE_DATE_REQUEST"
    TASK_CHILD_CREATE = "TASK_CHILD_CREATE"
    TASK_CONTROL_CREATE = "TASK_CONTROL_CREATE"
    TASK_CONTROL_UPDATE = "TASK_CONTROL_UPDATE"
    TASK_CONTROL_REMOVE = "TASK_CONTROL_REMOVE"
    TASK_CONTROL_DELETE = "TASK_CONTROL_DELETE"
    TASK_AUTHOR_CHANGE = "TASK_AUTHOR_CHANGE"
    TASK_EXECUTE_ALL = "TASK_EXECUTE_ALL"
    DOCUMENT_TASK_ENDLESS = "DOCUMENT_TASK_ENDLESS"
    DOCUMENT_TASK_PERIOD = "DOCUMENT_TASK_PERIOD"
    TASK_TASK_PROJECT_CREATE = "TASK_TASK_PROJECT_CREATE"
    TASK_TASK_PROJECT_EXECUTE_BY_AUTHOR = "TASK_TASK_PROJECT_EXECUTE_BY_AUTHOR"
    DOCUMENT_TASK_ROOT_DELETE = "DOCUMENT_TASK_ROOT_DELETE"
    TASK_PROJECT_AUTHOR_CHANGE = "TASK_PROJECT_AUTHOR_CHANGE"
    TASK_PROJECT_DELETE = "TASK_PROJECT_DELETE"
    TASK_PROJECT_EXECUTOR_UPDATE = "TASK_PROJECT_EXECUTOR_UPDATE"
    TASK_PROJECT_UPDATE = "TASK_PROJECT_UPDATE"
    TASK_PROJECT_EXECUTE = "TASK_PROJECT_EXECUTE"
    DOCUMENT_ADDITIONAL_DOCUMENT_CREATE = "DOCUMENT_ADDITIONAL_DOCUMENT_CREATE"
    DOCUMENT_ADDITIONAL_DOCUMENT_CREATE_CHILD = "DOCUMENT_ADDITIONAL_DOCUMENT_CREATE_CHILD"
    DOCUMENT_ADDITIONAL_DOCUMENT_UPDATE = "DOCUMENT_ADDITIONAL_DOCUMENT_UPDATE"
    DOCUMENT_ADDITIONAL_DOCUMENT_DELETE = "DOCUMENT_ADDITIONAL_DOCUMENT_DELETE"
    DOCUMENT_CONTROL_POINT_CREATE = "DOCUMENT_CONTROL_POINT_CREATE"
    DOCUMENT_CONTROL_POINT_MOVE = "DOCUMENT_CONTROL_POINT_MOVE"
    CONTROL_POINT_UPDATE = "CONTROL_POINT_UPDATE"
    CONTROL_POINT_COMPLETE = "CONTROL_POINT_COMPLETE"
    CONTROL_POINT_REVISION = "CONTROL_POINT_REVISION"
    CONTROL_POINT_DELETE = "CONTROL_POINT_DELETE"


# ══════════════════════════════════════════════════════════════════════════════
# Nomenclature & Archive Enums
# ══════════════════════════════════════════════════════════════════════════════

class StoreAttribute(StrEnum):
    PERMANENT = "PERMANENT"
    TEMPORARY = "TEMPORARY"
    END_OF_NEED = "END_OF_NEED"
    BY_STAFF = "BY_STAFF"


class StorageType(StrEnum):
    ARCHIVE = "ARCHIVE"
    OPERATIONAL = "OPERATIONAL"


class MethodAssemblyType(StrEnum):
    ED = "ED"
    GD = "GD"
    PAPER = "PAPER"
    IR = "IR"


class GroupByStoragePeriod(StrEnum):
    S_T_UP_TO_10_Y = "S_T_UP_TO_10_Y"
    S_T_OVER_10_Y = "S_T_OVER_10_Y"
    P_S = "P_S"


class YearPostfix(StrEnum):
    YEAR_1 = "год"
    YEAR_2 = "года"
    YEAR_5 = "лет"


class StoragePeriodType(StrEnum):
    NUMERIC = "Числовой"
    PERMANENT = "Постоянно"
    UNTIL_NEEDED = "До минования надобности"
    UNTIL_REPLACED = "До замены новыми"


class NomenclatureStatus(StrEnum):  # Status6
    FORMING = "FORMING"
    COMPLETED = "COMPLETED"
    CLOSED = "CLOSED"
    ARCHIVE = "ARCHIVE"
    DESTROYED = "DESTROYED"


class NomenclatureDepartmentStatus(StrEnum):
    NEW = "NEW"
    SIGNING = "SIGNING"
    SIGNED = "SIGNED"
    AGREEMENT = "AGREEMENT"
    AGREED = "AGREED"
    DELETED = "DELETED"
    CANCEL = "CANCEL"


class SummaryNomenclatureDepartmentStatus(StrEnum):
    DRAFT = "DRAFT"
    NEW = "NEW"
    SIGNING = "SIGNING"
    SIGNED = "SIGNED"
    STATEMENT = "STATEMENT"
    APPROVED = "APPROVED"
    REJECT = "REJECT"
    CANCEL = "CANCEL"


class DestructionActStatus(StrEnum):
    NEW = "NEW"
    AGREEMENT = "AGREEMENT"
    AGREED = "AGREED"
    SIGNING = "SIGNING"
    SIGNED = "SIGNED"
    STATEMENT = "STATEMENT"
    APPROVED = "APPROVED"
    CANCEL = "CANCEL"


class AcceptanceInventoryStatus(StrEnum):
    NEW = "NEW"
    SIGNING = "SIGNING"
    SIGNED = "SIGNED"
    STATEMENT = "STATEMENT"
    APPROVED = "APPROVED"
    AGREEMENT = "AGREEMENT"
    AGREED = "AGREED"
    REJECT = "REJECT"
    CANCEL = "CANCEL"


class NomenclatureType(StrEnum):
    MAIN = "MAIN"
    ADDITIONAL = "ADDITIONAL"


class ExpertiseType(StrEnum):
    EPK = "EPK"
    CEK = "CEK"
    EK = "EK"


# ══════════════════════════════════════════════════════════════════════════════
# Employee & Access Enums
# ══════════════════════════════════════════════════════════════════════════════

class RoleObjectType(StrEnum):  # Type14
    DOCUMENT = "DOCUMENT"
    TASK = "TASK"
    TASK_PROJECT = "TASK_PROJECT"
    NOMENCLATURE_DEPARTMENT = "NOMENCLATURE_DEPARTMENT"
    SUMMARY_NOMENCLATURE_DEPARTMENT = "SUMMARY_NOMENCLATURE_DEPARTMENT"
    DESTRUCTION_ACT = "DESTRUCTION_ACT"
    NOMENCLATURE_AFFAIR = "NOMENCLATURE_AFFAIR"
    MINI_DOCUMENT = "MINI_DOCUMENT"
    SYSTEM = "SYSTEM"
    ACCEPTANCE_INVENTORY = "ACCEPTANCE_INVENTORY"
    CUSTOM = "CUSTOM"
    ADDITIONAL_DOCUMENT = "ADDITIONAL_DOCUMENT"
    CONTRACT = "CONTRACT"


class RoleType(StrEnum):
    SYSTEM = "SYSTEM"
    USER = "USER"


class Merge(StrEnum):
    ALL = "ALL"
    SELF = "SELF"
    SELF_AND_IO = "SELF_AND_IO"
    SUBORDINATES_AND_SELF = "SUBORDINATES_AND_SELF"
    SUBORDINATES_AND_SELF_AND_IO = "SUBORDINATES_AND_SELF_AND_IO"


class ResolvePolicy(StrEnum):
    ANY = "ANY"
    MERGE = "MERGE"


class PermissionType(StrEnum):
    SYSTEM = "SYSTEM"
    DIRECTORY = "DIRECTORY"


class ActionTypeQueue(StrEnum):
    ANY = "ANY"
    ORDERED = "ORDERED"


class GroupType(StrEnum):  # Type7
    ACCESS = "ACCESS"
    DISTRIBUTION = "DISTRIBUTION"


class BlockedField(StrEnum):
    FIRST_NAME = "FIRST_NAME"
    LAST_NAME = "LAST_NAME"
    MIDDLE_NAME = "MIDDLE_NAME"
    POST = "POST"
    PHONE = "PHONE"
    EMAIL = "EMAIL"
    PHOTO = "PHOTO"
    DEPARTMENT = "DEPARTMENT"


class EmployeeCreateType(StrEnum):
    MANUAL = "MANUAL"
    LDAP = "LDAP"
    SYSTEM = "SYSTEM"


class UserActionType(StrEnum):
    """Available user action types."""
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    SEARCH = "SEARCH"
    DOCUMENT_VIEW = "DOCUMENT_VIEW"
    # Add more as needed, common types used in dashboard


class CorrespondentType(StrEnum):  # Type2
    NORMAL = "NORMAL"
    AISMV = "AISMV"
    DIRECTUM = "DIRECTUM"
    GTB_ORG = "GTB_ORG"


class DeclarantType(StrEnum):
    INDIVIDUAL = "INDIVIDUAL"
    ENTITY = "ENTITY"


class AppealType(StrEnum):
    REPEAT = "REPEAT"
    IDENTICAL = "IDENTICAL"


class SubmissionFormAppeal(StrEnum):
    WRITTEN = "WRITTEN"
    ELECTRONIC = "ELECTRONIC"
    VERBAL = "VERBAL"


class FormMeetingType(StrEnum):
    INTRAMURAL = "INTRAMURAL"
    POLLING_METHOD = "POLLING_METHOD"


# ══════════════════════════════════════════════════════════════════════════════
# Task & Report Enums
# ══════════════════════════════════════════════════════════════════════════════

class TaskStatus(StrEnum):
    ON_EXECUTION = "ON_EXECUTION"
    EXECUTED = "EXECUTED"


class TaskType(StrEnum):  # Type12
    INFORMATION = "INFORMATION"
    GENERAL = "GENERAL"


class Period(StrEnum):
    DAY = "DAY"
    WEEK = "WEEK"
    MONTH = "MONTH"
    THREE_MONTHS = "THREE_MONTHS"
    SIX_MONTHS = "SIX_MONTHS"
    YEAR = "YEAR"


class PanelType(StrEnum):
    ACTIVE_USER = "ACTIVE_USER"
    DOCUMENT_CREATE = "DOCUMENT_CREATE"
    DOCUMENT_REGISTERED = "DOCUMENT_REGISTERED"


class ReportType(StrEnum):  # Type16
    DOC = "DOC"
    TASK = "TASK"


class ReportColumn(StrEnum):
    DOC_PROFILE = "DOC_PROFILE"
    DOC_TYPE = "DOC_TYPE"
    DOC_CATEGORY = "DOC_CATEGORY"
    DATE_REG = "DATE_REG"
    AUTHOR_DOC = "AUTHOR_DOC"
    REG_NUMBER = "REG_NUMBER"
    DESTINATION = "DESTINATION"
    CORRESPONDENT = "CORRESPONDENT"
    OUTGOING_NUMBER = "OUTGOING_NUMBER"
    OUTGOING_DATE = "OUTGOING_DATE"
    SIGNED_BY = "SIGNED_BY"
    STATUS = "STATUS"
    EXECUTOR_STAGE = "EXECUTOR_STAGE"
    DATE_STAGE = "DATE_STAGE"
    AUTHOR_TASK = "AUTHOR_TASK"
    TASK_EXECUTOR = "TASK_EXECUTOR"
    TASK_LEADER = "TASK_LEADER"
    TASK_NUMBER = "TASK_NUMBER"
    DOC_SHORT_SUMMARY = "DOC_SHORT_SUMMARY"
    DATE_TASK_EXECUTE = "DATE_TASK_EXECUTE"
    TASK_ON_CONTROL = "TASK_ON_CONTROL"
    DOC_ON_CONTROL = "DOC_ON_CONTROL"
    DOC_DATE_CONTROL = "DOC_DATE_CONTROL"
    REPORT_TASK = "REPORT_TASK"
    TASK_SHORT_SUMMARY = "TASK_SHORT_SUMMARY"
    CONTRACT_SIGNING_DATE = "CONTRACT_SIGNING_DATE"
    CONTRACT_START_DATE = "CONTRACT_START_DATE"
    CONTRACT_DAYS_TO_COMPLETION = "CONTRACT_DAYS_TO_COMPLETION"
    CONTRACT_SUM = "CONTRACT_SUM"
    CURRENCY = "CURRENCY"
    CONTRACT_RECIPIENT = "CONTRACT_RECIPIENT"


# ══════════════════════════════════════════════════════════════════════════════
# Notification Enums
# ══════════════════════════════════════════════════════════════════════════════

class ReminderType(StrEnum):  # Id в RemindersRulesDto
    DEADLINE_CONTROL_DOCUMENT = "DEADLINE_CONTROL_DOCUMENT"
    DEADLINE_CONTROL_TASK = "DEADLINE_CONTROL_TASK"
    DEADLINE_EXECUTION_PROCESS = "DEADLINE_EXECUTION_PROCESS"
    DEADLINE_EXECUTION_TASK = "DEADLINE_EXECUTION_TASK"
    INACTION_SUMMARY_NOMENCLATURE = "INACTION_SUMMARY_NOMENCLATURE"
    INACTION_NOMENCLATURE_DEPARTMENT = "INACTION_NOMENCLATURE_DEPARTMENT"
    INACTION_DESTRUCTION_ACT = "INACTION_DESTRUCTION_ACT"
    INACTION_ACCEPTANCE_INVENTORY = "INACTION_ACCEPTANCE_INVENTORY"
    DEADLINE_CONTRACT_DURATION_END = "DEADLINE_CONTRACT_DURATION_END"
    DEADLINE_EXECUTION_DOCUMENT_CONTROL_POINT = "DEADLINE_EXECUTION_DOCUMENT_CONTROL_POINT"


class ContentType(StrEnum):
    JSON = "application/json"
    TEXT = "text/plain"
    PDF = "application/pdf"


class RecognitionFileTypeEnum(StrEnum):
    PDF = "PDF"
    JPG = "JPG"
    PNG = "PNG"


class RecognitionLanguageEnum(StrEnum):
    RUS = "rus"
    ENG = "eng"
    BEL = "bel"
